# docker-compose.yml

# The 'version' tag is optional in newer Docker Compose versions, but harmless.
version: '3.8'


services:
  # --- Service #1: The Qdrant Database Service ---
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    # This 'volumes' section mounts a local directory into the container.
    # Use a named volume for persistent storage, managed by Docker.
    volumes:
      - ./qdrant_storage:/qdrant/storage
    container_name: qdrant_db
    networks:
      - agent_network
    # Ensures the api service only starts after Qdrant is fully operational, not just when the container has started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3

  # --- Service #2: The Python Application Service
  api:
    # Build and run using the amd64 platform for maximum compatibility on Apple Silicon.
    platform: linux/amd64
    build:  # Build the image from the Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Pass environment variables from the local .env file into the container.
    env_file:
      - .env
    # This makes the 'api' service wait for the 'qdrant' service to start.
    depends_on:
      - qdrant
    container_name: rag_api_service
    networks:
      - agent_network
    # ADD THIS SECTION TO OVERRIDE THE URL from QDRANT_URL="http://localhost:6333" (.env -- for local Terminal running)
    environment:
      - QDRANT_URL=http://qdrant:6333


# --- Top-Level Definitions ---
# These must be at the root of the file (no indentation).

# Define the shared network for our services to communicate
networks:
  agent_network:
    driver: bridge

# Define the named volume for Qdrant's data to be stored persistently
volumes:
  qdrant_storage:
