# config/config.yaml

vector_db:
  type: qdrant
  url: ${QDRANT_URL}
  prefer_grpc: false


llm:
  default: openai
  openai:
    chat_model: gpt-4o
    embedding_model: text-embedding-3-small
    api_key_env: OPENAI_API_KEY
  ollama:
    url: ${OLLAMA_URL}
    model: llama2
    embedding_model: nomic-embed-text


agent:
  framework: crewai
  max_iteraction: 3
  

retriever:
  k: 4    # Number of documents to retrieve